"""create_table

Revision ID: 1a1ad733848f
Revises: 
Create Date: 2023-05-11 00:18:25.153711

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a1ad733848f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jbi_items',
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('href', sa.String(), nullable=False),
                    sa.Column('parent_1', sa.String(), nullable=False),
                    sa.Column('parent_2', sa.String(), nullable=False),
                    sa.Column('parent_3', sa.String(), nullable=False),
                    sa.Column('parent_4', sa.String(), nullable=False),
                    sa.Column('parameters', sa.String(), nullable=False),
                    sa.Column('image', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('href')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jbi_items')
    # ### end Alembic commands ###
