"""empty message

Revision ID: 50a375d0af63
Revises: 1a1ad733848f
Create Date: 2023-05-15 03:56:13.158780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a375d0af63'
down_revision = '1a1ad733848f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jbi_items', sa.Column('is_saved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jbi_items', 'is_saved')
    # ### end Alembic commands ###
