"""a

Revision ID: 8af2e47ebfc7
Revises: ac726a522e10
Create Date: 2023-05-19 04:06:20.618243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af2e47ebfc7'
down_revision = 'ac726a522e10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jbi_fails', sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jbi_fails', 'is_saved')
    # ### end Alembic commands ###
