"""empty message

Revision ID: dac48874b25f
Revises: 50a375d0af63
Create Date: 2023-05-15 06:21:18.948430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac48874b25f'
down_revision = '50a375d0af63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jbi_fails',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('image')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jbi_fails')
    # ### end Alembic commands ###
